<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\BookController;
use App\Http\Controllers\BorrowController;
use App\Http\Controllers\CourseController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\LibrarySettingsController;
use App\Http\Controllers\LibrarianController;
use App\Http\Controllers\ReportController;
use Illuminate\Support\Facades\Route;

Route::get('/', fn () => response()->json(['message' => 'API Server Running']));
Route::get('/books/get_books.php', [BookController::class, 'index']);
Route::get('/books/get_categories.php', [BookController::class, 'categories']);
Route::get('/books/get_book_copies.php', [BookController::class, 'copies'])->middleware('api.token');
Route::match(['GET', 'POST'], '/books/get_book_courses.php', [BookController::class, 'courses'])->middleware('api.token');
Route::get('/books/get_book_status.php', [BookController::class, 'status'])->middleware('api.token');
Route::post('/books/add_book.php', [BookController::class, 'store'])->middleware(['api.token', 'role:Librarian,Director']);
Route::match(['POST', 'PUT'], '/books/update_book.php', [BookController::class, 'update'])->middleware(['api.token', 'role:Librarian,Director']);
Route::match(['POST', 'DELETE'], '/books/delete_book.php', [BookController::class, 'destroy'])->middleware(['api.token', 'role:Librarian,Director']);
Route::post('/books/upload_pdf.php', [BookController::class, 'uploadPdf'])->middleware(['api.token', 'role:Librarian,Director']);
Route::post('/books/upload_request_pdf.php', [BookController::class, 'uploadRequestPdf'])->middleware(['api.token', 'role:Librarian,Director']);
Route::post('/books/upload_cover_image.php', [BookController::class, 'uploadCoverImage'])->middleware(['api.token', 'role:Librarian,Director']);
Route::post('/books/update_book_image.php', [BookController::class, 'updateCoverImage'])->middleware(['api.token', 'role:Librarian,Director']);
Route::get('/books/download_pdf.php', [BookController::class, 'downloadPdf']);
Route::post('/books/request_book.php', [BookController::class, 'requestAddition'])->middleware(['api.token', 'request.user']);
Route::get('/books/get_request_details.php', [BookController::class, 'additionRequestDetails'])->middleware('api.token');
Route::post('/books/update_addition_request.php', [BookController::class, 'updateAdditionRequest'])->middleware(['api.token', 'role:Librarian,Director']);
Route::post('/books/approve_request.php', [BookController::class, 'approveAdditionRequest'])->middleware(['api.token', 'role:Librarian,Director']);
Route::post('/books/decline_request.php', [BookController::class, 'declineAdditionRequest'])->middleware(['api.token', 'role:Librarian,Director']);
Route::post('/books/reserve_book.php', [BorrowController::class, 'reserve'])->middleware(['api.token', 'request.user']);
Route::post('/books/cancel_reservation.php', [BorrowController::class, 'cancelReservation'])->middleware(['api.token', 'request.user']);
Route::post('/borrow/request_borrow.php', [BorrowController::class, 'request'])->middleware(['api.token', 'request.user']);
Route::post('/borrow/borrow_book.php', [BorrowController::class, 'request'])->middleware(['api.token', 'request.user']);
Route::post('/borrow/request_return.php', [BorrowController::class, 'requestReturn'])->middleware(['api.token', 'request.user']);
Route::post('/borrow/cancel_request.php', [BorrowController::class, 'cancelRequest'])->middleware(['api.token', 'request.user']);
Route::post('/borrow/return_book.php', [BorrowController::class, 'returnBook'])->middleware(['api.token', 'request.user']);
Route::post('/librarian/approve_borrow_request.php', [BorrowController::class, 'approveBorrowRequest'])->middleware(['api.token', 'role:Librarian,Director']);
Route::post('/librarian/reject_borrow_request.php', [BorrowController::class, 'rejectBorrowRequest'])->middleware(['api.token', 'role:Librarian,Director']);
Route::get('/librarian/get_available_copies.php', [BookController::class, 'availableCopies'])->middleware(['api.token', 'role:Librarian,Director']);
Route::post('/librarian/approve_return_request.php', [LibrarianController::class, 'approveReturnNotification'])->middleware(['api.token', 'role:Librarian,Director']);
Route::get('/librarian/dashboard_stats.php', [LibrarianController::class, 'dashboard'])->middleware(['api.token', 'role:Librarian,Director']);
Route::get('/librarian/get_requests.php', [LibrarianController::class, 'requests'])->middleware(['api.token', 'role:Librarian,Director']);
Route::get('/librarian/get_transaction_history.php', [LibrarianController::class, 'transactionHistory'])->middleware(['api.token', 'role:Librarian,Director']);
Route::match(['GET', 'POST', 'PUT', 'DELETE'], '/librarian/manage_shelves.php', [LibrarianController::class, 'shelves'])->middleware(['api.token', 'role:Librarian,Director']);
Route::get('/librarian/test_requests_sync.php', [LibrarianController::class, 'syncStatus'])->middleware(['api.token', 'role:Librarian,Director']);
Route::match(['GET', 'POST'], '/books/get_user_reservations.php', [BorrowController::class, 'userReservations'])->middleware(['api.token', 'request.user']);
Route::match(['GET', 'POST'], '/borrow/get_user_transactions.php', [BorrowController::class, 'userTransactions'])->middleware(['api.token', 'request.user']);
Route::get('/courses/list_courses.php', [CourseController::class, 'index']);
Route::get('/courses/search_courses.php', [CourseController::class, 'index']);
Route::post('/courses/add_course.php', [CourseController::class, 'store'])->middleware(['api.token', 'role:Librarian,Director']);
Route::post('/courses/edit_course.php', [CourseController::class, 'update'])->middleware(['api.token', 'role:Librarian,Director']);
Route::post('/courses/delete_course.php', [CourseController::class, 'destroy'])->middleware(['api.token', 'role:Librarian,Director']);
Route::get('/payments/get_user_fines.php', [PaymentController::class, 'fines'])->middleware(['api.token', 'request.user']);
Route::get('/payments/get_payment_history.php', [PaymentController::class, 'history'])->middleware(['api.token', 'request.user']);
Route::get('/payments/get_payments.php', [PaymentController::class, 'history'])->middleware(['api.token', 'request.user']);
Route::post('/payments/process_payment.php', [PaymentController::class, 'process'])->middleware(['api.token', 'request.user']);
Route::post('/reports/generate_report.php', [ReportController::class, 'generate'])->middleware(['api.token', 'role:Librarian,Director']);
Route::get('/settings/get_library_settings.php', [LibrarySettingsController::class, 'index']);
Route::match(['POST', 'PUT'], '/settings/update_library_settings.php', [LibrarySettingsController::class, 'update'])->middleware(['api.token', 'role:Librarian,Director']);

Route::prefix('v1')->group(function () {
    Route::post('/auth/login', [AuthController::class, 'login']);
    Route::post('/auth/register', [AuthController::class, 'sendRegistrationOtp']);
    Route::post('/auth/forgot-password', [AuthController::class, 'forgotPassword']);
    Route::post('/auth/reset-password', [AuthController::class, 'resetPassword']);
    Route::middleware('api.token')->group(function () {
        Route::get('/auth/me', [AuthController::class, 'me']);
        Route::get('/auth/session', [AuthController::class, 'session']);
        Route::post('/auth/logout', [AuthController::class, 'logout']);
        Route::post('/auth/change-password', [AuthController::class, 'changePassword']);
        Route::post('/borrow/requests', [BorrowController::class, 'request'])->middleware('permission:borrow.request');
    });
    Route::get('/books', [BookController::class, 'index']);
    Route::get('/books/{book}', [BookController::class, 'show']);
});

Route::post('/auth/login.php', [AuthController::class, 'login']);
Route::post('/auth/register.php', [AuthController::class, 'sendRegistrationOtp']);
Route::post('/auth/send_register_otp.php', [AuthController::class, 'sendRegistrationOtp']);
Route::post('/auth/verify_email.php', [AuthController::class, 'verifyRegistrationOtp']);
Route::post('/auth/set_password.php', [AuthController::class, 'setRegistrationPassword']);
Route::post('/auth/send_reset_otp.php', [AuthController::class, 'sendPasswordResetOtp']);
Route::post('/auth/verify_reset_otp.php', [AuthController::class, 'verifyPasswordResetOtp']);
Route::post('/auth/reset_password.php', [AuthController::class, 'resetPasswordWithOtp']);
Route::post('/auth/change_password.php', [AuthController::class, 'changePasswordLegacy'])->middleware(['api.token', 'request.user']);
Route::match(['GET', 'POST'], '/auth/get_profile.php', [AuthController::class, 'getProfile'])->middleware(['api.token', 'request.user']);
Route::match(['GET', 'POST'], '/auth/get_notifications.php', [AuthController::class, 'getNotifications'])->middleware(['api.token', 'request.user']);
Route::post('/auth/update_profile.php', [AuthController::class, 'updateProfile'])->middleware(['api.token', 'request.user']);
Route::post('/auth/mark_notification_read.php', [AuthController::class, 'markNotificationRead'])->middleware(['api.token', 'request.user']);
Route::post('/auth/delete_notification.php', [AuthController::class, 'deleteNotification'])->middleware(['api.token', 'request.user']);
Route::post('/auth/upload_profile_image.php', [AuthController::class, 'uploadProfileImage'])->middleware(['api.token', 'request.user']);
Route::get('/auth/get_image.php', [AuthController::class, 'getImage']);
Route::get('/serve_image.php', [AuthController::class, 'serveImage']);
Route::match(['GET', 'POST'], '/auth/get_student_dashboard.php', [AuthController::class, 'studentDashboard'])->middleware(['api.token', 'request.user']);
Route::match(['GET', 'POST'], '/auth/send_notifications.php', [AuthController::class, 'sendReminders'])->middleware(['api.token', 'role:Librarian,Director']);
