<?php

return [
    'default' => env('DB_CONNECTION', 'mysql'),
    'connections' => [
        'mysql' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', env('DB_NAME', 'iit_shelf')),
            'username' => env('DB_USERNAME', env('DB_USER', '')),
            'password' => env('DB_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'prefix_indexes' => true,
            'strict' => true,
            'engine' => null,
        ],
        'auth_temp' => [
            'driver' => 'mysql',
            'host' => env('AUTH_TEMP_DB_HOST', env('DB_HOST', '127.0.0.1')),
            'port' => env('AUTH_TEMP_DB_PORT', env('DB_PORT', '3306')),
            'database' => env('AUTH_TEMP_DB_DATABASE', 'iit_shelf_auth_temp'),
            'username' => env('AUTH_TEMP_DB_USERNAME', env('DB_USERNAME', env('DB_USER', ''))),
            'password' => env('AUTH_TEMP_DB_PASSWORD', env('DB_PASSWORD', '')),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'prefix_indexes' => true,
            'strict' => true,
        ],
        'preregistration' => [
            'driver' => 'mysql',
            'host' => env('PREREG_DB_HOST', env('DB_HOST', '127.0.0.1')),
            'port' => env('PREREG_DB_PORT', env('DB_PORT', '3306')),
            'database' => env('PREREG_DB_DATABASE', 'iit_shelf_prereg'),
            'username' => env('PREREG_DB_USERNAME', env('DB_USERNAME', env('DB_USER', ''))),
            'password' => env('PREREG_DB_PASSWORD', env('DB_PASSWORD', '')),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'prefix_indexes' => true,
            'strict' => true,
        ],
    ],
    'migrations' => ['table' => 'migrations', 'update_date_on_publish' => true],
];
?>
